GET http://localhost:8080/

###

GET http://localhost:8080/accounts

###

GET http://localhost:8080/operations

###

POST http://localhost:8080/transfer
Content-Type: application/json

{
  "cardFromNumber": "1111222233334446",
  "cardFromValidTill": "0122",
  "cardFromCVV": "111",
  "cardToNumber": "4444333322221111",
  "amount": {
    "value": 1000,
    "currency": "euro"
  }
}

###

POST http://localhost:8080/transfer
Content-Type: application/json

{
  "cardFromNumber": "4444333322221111",
  "cardFromValidTill": "1221",
  "cardFromCVV": "111",
  "cardToNumber": "1111222233334444",
  "amount": {
    "value": 1000,
    "currency": "rub"
  }
}

###

POST http://localhost:8080/confirmOperation
Content-Type: application/json

{
  "operationId": "67",
  "code": "password"
}

###

POST http://localhost:8080/newaccount
Content-Type: application/json

{
  "cardNumber": "1111222233334446",
  "cardFromValidTill": "0122",
  "cardFromCVV": "111",
  "balance": {
    "value": 10000,
    "currency": "euro"
  }
}

###

POST http://localhost:8080/newaccount
Content-Type: application/json

{
"cardNumber": "4444333322221111",
"cardFromValidTill": "1221",
"cardFromCVV": "111",
"balance": {
"value": 10000,
"currency": "rub"
}
}

###

POST http://localhost:8080/put
Content-Type: application/json

{
"cardFromNumber": "4444333322221111",
"amount": 2000
}

###

