version: "3.7"
services:
  database:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - "./db/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=1


  task_app:
    build: .
    links:
      - "database"
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=database
      - spring.datasource.url=jdbc:mysql://database:3306/socks?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=1

